"""Constants for the Elco Remocon-Net integration."""

DOMAIN = "elco_remocon"
CONF_GATEWAY_ID = "gateway_id"
CONF_ZONE = "zone"
CONF_FEATURES_PAYLOAD = "features_payload"
CONF_READ_STRATEGY = "read_strategy"

DEFAULT_ZONE = "1"
DEFAULT_SCAN_INTERVAL = 120
DEFAULT_REQUEST_RETRY_COUNT = 3
DEFAULT_REQUEST_RETRY_DELAY = 10
DEFAULT_ERROR_LOG_AFTER_FAILURES = 3

READ_STRATEGY_LEGACY_FIRST = "legacy_first"
READ_STRATEGY_BSB_FIRST = "bsb_first"
READ_STRATEGY_LEGACY_ONLY = "legacy_only"
READ_STRATEGY_BSB_ONLY = "bsb_only"
READ_STRATEGIES = [
	READ_STRATEGY_LEGACY_FIRST,
	READ_STRATEGY_BSB_FIRST,
	READ_STRATEGY_LEGACY_ONLY,
	READ_STRATEGY_BSB_ONLY,
]
DEFAULT_READ_STRATEGY = READ_STRATEGY_LEGACY_FIRST

# API mode values
MODE_PROTECTION = 0
MODE_AUTOMATIC = 1
MODE_REDUCTION = 2
MODE_COMFORT = 3
